PUT http://127.0.0.1:8081/gms/contentmgnt/announcement
Accept: */*
Content-Type: application/json
Token: ce53223f-52fa-4853-b4be-c24e721e9f94

{
    "id":240,
	"title":"AAAAAAAAAACCCCCCCCCA"
//,
//	"createUser":1,
//	"createTime":"2018-11-06 15:27:43",
//	"updateUser":1,
//	"updateTime":"2018-11-06 15:30:44"
}

<> 2018-11-08T104440.200.json
###

