###获取token
POST http://localhost:8081/gms/login
Accept: */*
Content-Type: application/json

{
  "username":"hzc",
  "password":"hzcsb"
}

<> 2018-11-26T034737.200.json

####参数说明#####
//id主键 Long id;
//卡名称 String name;
//面额 double denomination;
//卡类型 1:充值卡,2:兑换卡,3:会员卡 int cardType;
//自定义卡头 String cardHead;
//随机位数 int randomFigure;
//根据位数生成的随机数 String randomNumStr;
//卡头和随机数拼接的卡号 String cardId;
//充值卡使用间隔 int useInterval;
//充值卡代理可生成1:代理可以生成 0:代理不可生成 int generateByProxy;
//充值卡金豆 double goldenBean;
//充值卡经验 double experience;
//会员卡每日获得金币 double goldCoinEveryDay;
//会员卡领取时长 long drawDuration;
//会员卡图标 String icon;

###查询，分页参数pageIndex和pageSize默认必传
POST http://127.0.0.1:8081/gms/cardmgnt/retrieve
Accept: */*
Content-Type: application/json
Token: fcaafa21-d7c0-471b-8ba1-e1fbd8cdb6d8

{   "pageIndex":1,   "pageSize":15}

<> 2018-11-26T034750.200.json
<> 2018-11-26T033507.200.json
<> 2018-11-26T031353.200.json
<> 2018-11-25T095044.200.json

###创建充值卡 "cardType": 1,
POST http://127.0.0.1:8081/gms/cardmgnt/create
Accept: */*
Content-Type: application/json
Token: c9bd8c43-1a94-45c2-ade8-a46a19e20f21

{
    "name": "100元充值卡",
    "denomination": 100,
    //充值卡类型为1
    "cardType": 1,
    "cardHead": "100y",
    "randomFigure": 8,
    "useInterval":100,
    "goldenBean":1000,
    "experience":200,
    "generateByProxy":1
}

<> 2018-11-26T033554.200.json
<> 2018-11-26T033516.200.json

###创建兑换卡 "cardType": 2,
POST http://127.0.0.1:8081/gms/cardmgnt/create
Accept: */*
Content-Type: application/json
Token: c9bd8c43-1a94-45c2-ade8-a46a19e20f21

{
    "name": "100元兑换卡",
    "denomination": 100,
    //充值卡类型为1
    "cardType": 2,
    "cardHead": "100y",
    "randomFigure": 8
}

<> 2018-11-26T033608.200.json

###创建会员卡 "cardType": 3,
POST http://127.0.0.1:8081/gms/cardmgnt/create
Accept: */*
Content-Type: application/json
Token: c9bd8c43-1a94-45c2-ade8-a46a19e20f21

{
    "name": "100元会员卡",
    "denomination": 100,
    //充值卡类型为1
    "cardType": 3,
    "cardHead": "100y",
    "randomFigure": 8,
    "goldCoinEveryDay":666,
    "drawDuration":6,
    "icon":"aaa.icon"
}

<> 2018-11-26T033622.200.json

####更新部分字段，id必填；
PUT http://127.0.0.1:8081/gms/cardmgnt/update
Accept: */*
Content-Type: application/json
Token: c9bd8c43-1a94-45c2-ade8-a46a19e20f21

{
//id必填字段，其他非必填
  "id": 1066958827548610561,
  "name": "100元会员卡",
  "denomination": 101.0,
  "cardType": 3,
  "cardHead": "100y",
  "randomFigure": 9,
  "randomNumStr": "68175648",
  "cardId": "100y68175648",
  "useInterval": 0,
  "generateByProxy": 0,
  "goldenBean": 0.0,
  "experience": 0.0,
  "goldCoinEveryDay": 666.0,
  "drawDuration": 6,
  "icon": "aaa.icon",
  "createUser": 3,
  "createTime": "2018-11-26 15:36:22",
  "updateUser": null,
  "updateTime": null,
  "memberId": null
}

<> 2018-11-26T033714.200.json
<> 2018-11-25T095328.200.json

####删除卡类，/gms/cardmgnt/delete/{id} id必填；
DELETE http://127.0.0.1:8081/gms/cardmgnt/delete/100y471774
Accept: */*
Content-Type: application/json
Token: 179361dd-2afd-4f10-9462-4d520783fa08


<> 2018-11-26T034557.200.json
<> 2018-11-26T034442.200.json
<> 2018-11-26T034151.200.json
<> 2018-11-26T033911.200.json

###
